### ISSUE TITLE
Time in Dht22_InterruptHandler

### ISSUE THREAD

**Issue by bookghf** [petoknm/DHT22#5]
How i calculate time for set bitpos . where does i get the the reference

**Comment by petoknm** [comment]
Currently I am working on a new timing mechanism that would be much easier to configure. You can already see it in the README.md on the master branch in the `Timer setup` section. However I currently can't test any of it so it is still under development. I will therefore probably make a release of the old version that was working (on STM32F4) and not recommend to use the current master branch until I tested it. The old timing mechanism is complex and intimidating.

**Comment by bookghf** [comment]
Thank bro
