### ISSUE TITLE
STM32F0xx

### ISSUE THREAD

**Issue by laalex** [petoknm/DHT22#6]
Does this work as well on STM32F0xx series? I have tried to run the code, fixed most of the issues in order to compile but it seems that the values are always 0. 

I am using a DHT11 which has the same way of communication as well. 

Any input on this would be much appreciated.

**Comment by petoknm** [comment]
I am in the process of adding more debugging information like more descriptive error states so that it would be possible to know what exactly went wrong. The readings are 0 most likely because the `dht22_read_data` function returned `DHT22_ERROR` and that means that the values are invalid.

**Comment by laalex** [comment]
Thanks for your reply! As far as I can see from my debug, I always get the dht library in DHT22_BUSY state. Does this have to do with the fact that maybe there is a slight difference in timing (communication process) between DHT11 and DHT22?

**Comment by petoknm** [comment]
There shouldn't be any difference in the protocol... I am for example using AM2320 amd it works... But I know one person who has a similar issue as well... So it is definitely something I will need to fix... The state being busy must be because it hasn't finished receiving 40 bits of data but also hasn't failed the timing requirements... Can you check that the interrupt service routine for the timer input capture gets triggered?

**Comment by petoknm** [comment]
Also please make sure you follow the timer calibration settings as described in the README https://github.com/petoknm/DHT22/blob/master/README.md#timer-setup

**Comment by laalex** [comment]
I am sorry to ask this, I’m fairly new to this class of microcontrollers. I ama fraid that STM32F0xx famili has no SWV and I am currently debugging my variables on a LCD display. 

How should I check if  the routine gets triggered? Have any hint for this?

**Comment by petoknm** [comment]
I use openocd+gdb for debugging over swd... But you can also use a simple gpio pin and toggle it from the ISR and monitor it somehow(oscilloscope/logic analyzer/LED)

**Comment by laalex** [comment]
Right. Skipped timer calibration :). Will try this and follow up tomorrow with progress on this. Please let me know if I can help you with the code I have for STM32F0xx, maybe it’ll somehow help for your new release!

Thanks a lot for all the support

**Comment by laalex** [comment]
Hello again. I have set up the timer according to your specifications. Here is the timer configration:

>  TIM14
> Prescaler (16bit) 7
> Counter period 65535
> Counter Mode UP
> Polarity Selection Falling edge

The, this is my dht_config code related to the timer
```
dht_config.timer         =  &htim14;
dht_config.timer_channel = TIM_CHANNEL_1;
```
Also, in `stm32f0xx_it.c` I configured the following:
```
void TIM14_IRQHandler(void)
{
  /* USER CODE BEGIN TIM14_IRQn 0 */

  /* USER CODE END TIM14_IRQn 0 */
  HAL_TIM_IRQHandler(&htim14);
  /* USER CODE BEGIN TIM14_IRQn 1 */
  dht22_interrupt_handler(&dht);
  /* USER CODE END TIM14_IRQn 1 */
}
```

Here is the TIM14 init function:
```
/* TIM14 init function */
static void MX_TIM14_Init(void)
{

  TIM_IC_InitTypeDef sConfigIC;

  htim14.Instance = TIM14;
  htim14.Init.Prescaler = 7;
  htim14.Init.CounterMode = TIM_COUNTERMODE_UP;
  htim14.Init.Period = 65535;
  htim14.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
  htim14.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
  if (HAL_TIM_Base_Init(&htim14) != HAL_OK)
  {
    _Error_Handler(__FILE__, __LINE__);
  }

  if (HAL_TIM_IC_Init(&htim14) != HAL_OK)
  {
    _Error_Handler(__FILE__, __LINE__);
  }

  sConfigIC.ICPolarity = TIM_INPUTCHANNELPOLARITY_FALLING;
  sConfigIC.ICSelection = TIM_ICSELECTION_DIRECTTI;
  sConfigIC.ICPrescaler = TIM_ICPSC_DIV1;
  sConfigIC.ICFilter = 0;
  if (HAL_TIM_IC_ConfigChannel(&htim14, &sConfigIC, TIM_CHANNEL_1) != HAL_OK)
  {
    _Error_Handler(__FILE__, __LINE__);
  }

}
```

After all this, the code runs smoothly and compiles successfully. After doing a little  bit of debug, everything seems to run well but the data is never read from the sensor. Using STM Studio VariableDebug and also breakpoints into the code I found out that (according to your new code pushed today) the read function always returns the `DHT22_ERROR_BUSY` code. 

State is always DHT22_ERROR_BUSY, hum, temp, last_value are 0 and bitpos is always -1.

Am I missing something from this configuration? The DHT11 sensor works well on other boards I've tested. 

Any hint  for further investigation?

**Comment by laalex** [comment]
Also, another important thing is that in the `dht22.c` file I updated the `set_pin_in` and `set_pin_out`  accordingly to the values that the HAL lib has available for STM32F0XX. There is a difference in the `set_pin_in` I had to use `GPIO_MODE_AF_PP` for the mode value since I can't find `GPIO_MODE_AF_INPUT` defined in my HAL_GPIO library. `GPIO_MODE_AF_PP` is described as ` Alternate Function Push Pull Mode`. 
I have available also `GPIO_MODE_AF_OD`   (Alternate Function Open Drain Mode) and `GPIO_MODE_INPUT` (Input Floating Mode). I've tried to run the code with all the configurations mentioned but I get the same results.

Here is the definition from set_pin_in I currently use

```
static void set_pin_in(dht22* handle) {
    GPIO_InitTypeDef GPIO_InitStruct;
    GPIO_InitStruct.Pin  = handle->config.gpio_pin;
    GPIO_InitStruct.Pull = GPIO_PULLUP;
    GPIO_InitStruct.Mode  = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;

    HAL_GPIO_Init(handle->config.gpio_port, &GPIO_InitStruct);
}
```

**Comment by laalex** [comment]
Also, if this helps, I am using a 10k pull-up resistor on the data pin as indicated into the datasheet of DHT11.

**Comment by laalex** [comment]
I put a breakpoint in `dht22_interrupt_handler` function and it seems that it is never reached. Seems to  be an issue with the timer I suppose :)

**Comment by petoknm** [comment]
I think I'm going to create an example for STM32F0 and test it. I think I have some STM32F0 board (hopefully)...

**Comment by petoknm** [comment]
And yes, the pull-up on the data line is definitely recommended. Although could be implemented by the MCU's internal pull-up possibly.

**Comment by laalex** [comment]
I understand. Thanks for the information. This might be another dumb quest, but does the TIM assigned PIN has to do anything with the sensor? Is there a wiring that involves the clock pin as well with the sensor's data pin?

**Comment by petoknm** [comment]
The TIM input capture channel pin is the one that is communicating with the sensor. This library requires only one data pin and that pin has to be the timer input capture channel pin as described in the hardware setup https://github.com/petoknm/DHT22#hardware-setup

**Comment by laalex** [comment]
I've moved my wiring from PA2 pin to the PA7 pin (which is for TIM14 channel). I still get the same results, nothing working. I also have a PIR sensor connected to another PIN on the device, which works as expected. I tested and changed a few DHT11 sensors to make sure they are not broken, all are good and working with other boards.

I tried using 3.3V and 5V supply for the DHT11 (having ground of powersource, DHT11 and STM32F040 connected together).

All the configurations are exactly as you indicated yet it seems that it's not working.

**Comment by petoknm** [comment]
Ok... Im trying it on STM32F0 now and Im getting a timeout as well... seems like it is not getting the interrupts or something... Im going to investigate and let you know what was the issues once I figure it out.

**Comment by laalex** [comment]
Thank you very much! I hardly wait for your answer as this bugged me off at least 4 days already.

**Comment by petoknm** [comment]
Silly me... I forgot to register the `dht22_interrupt_handler` in the ISR of TIM14... I'll be pushing the STM32F0 example in the coming minutes... And it works.
![img_20180206_000722](https://user-images.githubusercontent.com/5087675/35833503-d957d1aa-0ad1-11e8-9368-50e830b09bf6.jpg)
![img_20180206_000708](https://user-images.githubusercontent.com/5087675/35833504-d96f3764-0ad1-11e8-82e8-a6f0482ec178.jpg)

**Comment by laalex** [comment]
Hopefully. I have the exact same board as you. I am waiting for the example to try.

**Comment by laalex** [comment]
Can you also please attach wiring diagram / text for the above image? And the .ioc file generated by CubeMX?

**Comment by petoknm** [comment]
I included the wiring description in the README for the example in `example/stm32f0` folder. There is also the .ioc file from the STM32CubeMX in there. You should be able to build the example just by running `make` in the `example/stm32f0` folder and then flashing the resulting `build/dht22.bin/elf` file

**Comment by petoknm** [comment]
Please let me know if the example is working for you.

**Comment by petoknm** [comment]
And if you are not using `make` to compile the example, remember to define `STM32F0`... I did it in the Makefile by adding a `-DSTM32F0` to the compiler flags.

**Comment by laalex** [comment]
Ok. I tried with this board, and it doesn’t work. I have a few tenth of them. Will soldier pins on a new board snd try on a fresh new one and will come back to you. 

Do you put 5V or 3.3V on the pull-up and data line?

**Comment by petoknm** [comment]
3.3V just like the Vcc of the sensor and the entire system... And also check the datasheet because on my sensor AM2320 which supports both I2C and this DHT22 protocol, I had to ground the third pin of the sensor to tell it to use DHT22 protocol instead of I2C... But that might differ based on the sensor you use

**Comment by laalex** [comment]
Hey. I've haven't tried your code yet but I configured from scratch in CubeMX a new project and only included your library and did all the configuration, still no luck having the timer triggered in any way. I suppose that the timer should be triggered by your code when the dht22_read function is called into the main loop and has nothing to do with the sensor and/or wiring. Is this correct?

I'll try to compile your code today and see if it's working exactly. Maybe I'm missing something in the CubeMX configuration part.

**Comment by petoknm** [comment]
The code works like the following:
1. The user calls `dht22_read_data`
2. Library sends the low signal for 2ms to the sensor
3. Library sets the pin as input and start the timer
4. When the pin goes low (falling edge input capture) the timer hardware triggers an interrupt
5. Timer ISR calls `dht22_interrupt_handler`
6. Library get the timing information and calculates if the bit was a 1 or a 0.

Steps 4-6 repeat until the library receives 40 bits or times out after 1 second. So the interrupt should fire whenever you bring the input capture channel pin low, done by hardware. If it doesn't than something is not configured correctly in hardware. You can look at the timer config in the .ioc example files.

**Comment by petoknm** [comment]
Fixed over gitter PM
